### ISSUE TITLE
Poor Accessibility

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#10]
Several user interface elements have a very poor contrast and are sometimes barely legible. With this being so obvious, we should check for other basic accessibility problems as well.

![5d36a1f6-0a79-4ea0-a4b1-63b8f32a30a6](https://github.com/UOS-RZ/deterrers/assets/1008395/66128429-fe05-47bf-b17c-f879b64ad19b)

![05bfe885-644e-4604-9ebd-693f921caac6](https://github.com/UOS-RZ/deterrers/assets/1008395/250608bf-8dc8-4c1b-a2af-1c6cc9f59680)

![936255d5-f9ca-413a-b4c7-e2333b215c72](https://github.com/UOS-RZ/deterrers/assets/1008395/ef5989c9-4507-4a06-be96-6499b0b1eee1)

![ba65876d-b0fa-4a16-9679-cb7c7cec6816](https://github.com/UOS-RZ/deterrers/assets/1008395/b2de57b7-3e00-470f-a7a7-733d0faabafa)

**Comment by tibroc** [comment]
I don't care about this issue, but for people who use the UI this is probably critical.

**Comment by nwintering** [comment]
@dennis531  I just realised that #24 introduced UI improvements for Google Chrome but introduced issues with the navigation bar and tab selection for Firefox:

![image](https://github.com/UOS-RZ/deterrers/assets/33374766/69d8d0a9-3a06-45ce-a1fe-723f1272bfe9)

**Comment by dennis531** [comment]
The website may be cached in your browser. Try opening the development console and disabling the cache.

**Comment by nwintering** [comment]
Ah you're right, worked like a charm

**Comment by nwintering** [comment]
Closed with 9daee8a
