### ISSUE TITLE
Usability: Meaning of Buttons

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#14]
Provide context information for buttons. You can find out about most buttons on the landing page, but having to look up functionality there is not a great user experience. Having parts of the explanation crossed out makes it even harder.

Looking at these options, a user should immediately understand what these options do and why they might not be available.

You don’t know that triggering an “Ordinary Scan” will deactivate other options unless it is too late. Though you also wouldn’t find out about that on the about page.

![aa1c4cd8-c0d5-46e3-8edf-47028a04b6d6](https://github.com/UOS-RZ/deterrers/assets/1008395/46d0aaf3-4d4a-4a74-84e0-8590f5ceb54b)

In this example, I have no idea why I cannot edit any details.

**Comment by lkiesow** [comment]
Some ideas for making the UI easier to understand:

- Separate local and perimeter firewall actions. Don't mix them. Make them completely separate panes. That way no one assumes that e.g. adding a port under „ Host-based Firewall Policies“ will add that port in the perimeter firewall (yes, people think that will happen)
- Use one button for the status (register/block). One of them is always deactivated anyway. or…
- …just use a single drop-down for the perimeter firewall status. We already have the empty profile which means that all traffic is being blocked. It's weird to have that *and* the block options
  - we happily use the empty profile since that makes things much more flexible for us. We still have our host scanned and we can quickly change the state.

**Comment by tibroc** [comment]
This is critical in terms of usability. People use this wrong and therefore it is broken. I would discard the firewall scripts completely. I hardly find a sesnible use case for them.

**Comment by dennis531** [comment]
For the "empty" internet service profile, I suggest a different name like "Scan+Block" or "Temporary blocked".

**Comment by nwintering** [comment]
I think, I would prefer something like "None" to show that no service is provided.
