### ISSUE TITLE
Actually useful naming

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#15]
Using the primary DNS entry for a name which (for UOS at least) usually contains a VM number is not helpful for identifying the host. We should use the `comment` field from Proteus instead. It should contain the name machines were originally registered with and can be updated by admins if necessary.

![Screenshot from 2023-07-27 22-31-15](https://github.com/UOS-RZ/deterrers/assets/1008395/b5190131-3e0f-4186-a1ac-86d2b47192d6)

**Comment by dennis531** [comment]
I suggest the following solutions:
- Show the comment (if present) in parentheses after all DNS names: e.g. `vm045.rz.uos.de (studip-test)`
- or add a new column for the comments (e.g. "comment")

@nwintering Do you have any preference?
