### ISSUE TITLE
Transactions or eventual consistency

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#21]
From time to time it seems to happen that users activate profiles in DETERRERS which are never committed to the actual firewall. This is a critical problem since users are misled what the firewall is set to. They cannot identify that the firewall rules are incorrect.

The only way to identify the incorrectly set firewall is to run into actual errors in production and then investigate by checking if ports are blocked from outside the network but not from inside. This is tedious work for technicians and causes issues for end users.

DETERRERS should either use transactions, and only set profiles when it's guaranteed that they are set correctly in the firewall.

If this is hard, an alternative would be to go for eventual consistency, mark the profile change as pending and update this state once the firewall has been updated. This process should be repeated and the actual state being checked on a regular basis to avoid that the state in DETERRERS and the firewall diverges.

**Comment by nwintering** [comment]
fixed with commit c9bb19235008f26b4ec8e4db1a2b1030edeff560
