### ISSUE TITLE
Move Host Details Table to "General" Tab

### ISSUE THREAD

**Issue by dennis531** [UOS-RZ/deterrers#25]
For further improvement, we could even transfer most of the "details"-table into the General-tab. Only the host-based firewall field would go into the "Host-based Firewall"-tab.
This would also mean that the selection of Internet Service Profile and Host-based Firewall program should be separated into different forms.

_Originally posted by @nwintering in https://github.com/UOS-RZ/deterrers/issues/24#issuecomment-1774718358_

**Comment by dennis531** [comment]
@nwintering Should it be possible to change the "Host-based Firewall" during a scan or the registration process?

**Comment by nwintering** [comment]
> @nwintering Should it be possible to change the "Host-based Firewall" during a scan or the registration process?

Yes, the "Host-based Firewall" should be editable but the Internet Service Profile not.
